# Generated by Django 4.1.7 on 2023-03-27 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_career_title_alter_person_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2, unique=True, verbose_name='Ограничение')),
            ],
            options={
                'verbose_name': 'Возрастное ограничение',
                'verbose_name_plural': 'Возрастное ограничение',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страна',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанр',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('tagline', models.CharField(default='', max_length=100, verbose_name='Слоган')),
                ('description', models.TextField(verbose_name='Описание')),
                ('poster', models.ImageField(upload_to='movies/images/', verbose_name='Постер')),
                ('year', models.PositiveSmallIntegerField(default=2023, verbose_name='Дата выхода')),
                ('rating', models.FloatField(verbose_name='Рейтинг')),
                ('timeline', models.IntegerField(help_text='Указывать продолжительность в минутах', verbose_name='Продолжительность')),
                ('poster_horizontal_with_text', models.ImageField(upload_to='movies/images/', verbose_name='Горизонтальный постер с названием')),
                ('poster_horizontal_without_text', models.ImageField(upload_to='movies/images/', verbose_name='Горизонтальный постер без названия')),
                ('movie', models.FileField(upload_to='movies/movies/', verbose_name='Файл фильма')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
            },
        ),
        migrations.AlterModelOptions(
            name='career',
            options={'verbose_name': 'Карьера', 'verbose_name_plural': 'Виды карьер'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Персона', 'verbose_name_plural': 'Персоны'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Расширенный пользователь', 'verbose_name_plural': 'Расширенные пользователи'},
        ),
        migrations.AddField(
            model_name='person',
            name='career',
            field=models.ManyToManyField(related_name='person_career', to='core.career', verbose_name='Карьера'),
        ),
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='persons/', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='users/', verbose_name='Аватар'),
        ),
        migrations.DeleteModel(
            name='PersonToCareer',
        ),
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(related_name='movie_actor', to='core.person', verbose_name='Актеры'),
        ),
        migrations.AddField(
            model_name='movie',
            name='ageLimit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.agelimit', verbose_name='Возрастное ограничение'),
        ),
        migrations.AddField(
            model_name='movie',
            name='country',
            field=models.ManyToManyField(related_name='movie_country', to='core.country', verbose_name='Страны'),
        ),
        migrations.AddField(
            model_name='movie',
            name='directors',
            field=models.ManyToManyField(related_name='movie_director', to='core.person', verbose_name='Режиссер'),
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(related_name='movie_genre', to='core.genre', verbose_name='Жанры'),
        ),
    ]
