# Generated by Django 4.1.7 on 2023-03-27 15:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_agelimit_country_genre_movie_alter_career_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonTVSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, verbose_name='Номер сезона')),
                ('year', models.PositiveSmallIntegerField(default=2023, verbose_name='Дата выхода')),
            ],
            options={
                'verbose_name': 'Сезон сериала',
                'verbose_name_plural': 'Сезоны сериала',
            },
        ),
        migrations.CreateModel(
            name='TVSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('tagline', models.CharField(default='', max_length=100, verbose_name='Слоган')),
                ('description', models.TextField(verbose_name='Описание')),
                ('poster', models.ImageField(upload_to='tvseries/images/', verbose_name='Постер')),
                ('rating', models.FloatField(verbose_name='Рейтинг')),
                ('poster_horizontal_with_text', models.ImageField(upload_to='tvseries/images/', verbose_name='Горизонтальный постер с названием')),
                ('poster_horizontal_without_text', models.ImageField(upload_to='tvseries/images/', verbose_name='Горизонтальный постер без названия')),
                ('actors', models.ManyToManyField(related_name='tvseries_actor', to='core.person', verbose_name='Актеры')),
                ('ageLimit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.agelimit', verbose_name='Возрастное ограничение')),
                ('country', models.ManyToManyField(related_name='tvseries_country', to='core.country', verbose_name='Страны')),
                ('directors', models.ManyToManyField(related_name='tvseries_director', to='core.person', verbose_name='Режиссер')),
                ('genres', models.ManyToManyField(related_name='tvseries_genre', to='core.genre', verbose_name='Жанры')),
            ],
            options={
                'verbose_name': 'Сериал',
                'verbose_name_plural': 'Сериалы',
            },
        ),
        migrations.CreateModel(
            name='SeriesTVSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, verbose_name='Номер серии')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('timeline', models.IntegerField(help_text='Указывать продолжительность в минутах', verbose_name='Продолжительность')),
                ('series', models.FileField(upload_to='tvseries/tvseries/', verbose_name='Файл серии')),
                ('date_publish', models.DateField(default=datetime.date.today, verbose_name='Дата выхода')),
                ('season_tvseries', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.seasontvseries', verbose_name='Сезон сериала')),
            ],
            options={
                'verbose_name': 'Серия сериала',
                'verbose_name_plural': 'Серии сериала',
            },
        ),
        migrations.AddField(
            model_name='seasontvseries',
            name='tvseries',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tvseries', verbose_name='Сериал'),
        ),
    ]
