# Generated by Django 4.1.7 on 2023-03-27 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_movie_title_image_tvseries_title_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='title_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='movies/title-images/', verbose_name='Название изображением'),
        ),
        migrations.AlterField(
            model_name='tvseries',
            name='title_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='tvseries/title-images/', verbose_name='Название изображением'),
        ),
    ]
