# Generated by Django 4.1.7 on 2023-03-27 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_movie_title_image_alter_tvseries_title_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='tagline',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Слоган'),
        ),
        migrations.AlterField(
            model_name='tvseries',
            name='tagline',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Слоган'),
        ),
    ]
