# Generated by Django 4.1.7 on 2023-03-27 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_movie_tagline_alter_tvseries_tagline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seriestvseries',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Название'),
        ),
    ]
